# Dev overrides
app:
  env: dev
logging:
  level: DEBUG
  format: human
  structured: true
etl:
  behavior:
    download_images: false
ingest:
  # Smaller batch size for dev environment
  batch_size: 100
  parallel_workers: 1
