name: etl-cron
on:
  # run every 3 hours
  schedule:
    - cron: "0 */3 * * *"
  # allow manual triggering for testing
  workflow_dispatch:

permissions:
  contents: write

jobs:
  etl:
    # NOTE: This job is gated at runtime by `ETL_RUN_ENABLED` repository Variable.
    # We avoid job-level expressions to keep editors happy; the first step will skip when disabled.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check ETL enabled
        run: |
          if [ "${ETL_RUN_ENABLED:-false}" != "true" ]; then
            echo "ETL_RUN_ENABLED != true — skipping ETL job"
            exit 0
          fi
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -U pip && pip install .
      
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Run ETL (prod)
        working-directory: ${{ github.workspace }}
        run: |
          python -m news_mvp.cli etl run --source ynet --env prod
          python -m news_mvp.cli etl run --source hayom --env prod
          python -m news_mvp.cli etl run --source haaretz --env prod
          python -m news_mvp.cli etl merge --env prod

      - name: Debug List data/pics contents
        run: |
          echo "Listing all data/pics/{date}/{source} directories and files:"
          find data/pics -type d
          find data/pics -type f
          ls -lR data/pics || true
          echo "Listing data/pics/ynet, hayom, haaretz subdirs:"
          ls -l data/pics/ynet || true
          ls -l data/pics/hayom || true
          ls -l data/pics/haaretz || true
      
      - name: Check for changes and commit
        run: |
          git add -A
          git commit -m "feat: Update master CSV files and images

          - Updated master CSV files with latest news data  
          - Added/updated article images
          - Auto-generated by ETL pipeline on $(date -u +'%Y-%m-%d %H:%M UTC')

          Sources: ynet, hayom, haaretz
          " || echo "No changes to commit"
          git push -f
